# 本地开发环境配置
spring:
  application:
    name: myweb_backend
  datasource:
    url: jdbc:mysql://localhost:3306/myweb
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
blog_image:
  upload-dir: D:\\develop\\myweb_backend_blog_imgs
  image-url: /images/
  base-url: http://localhost:8080